jest.mock('@octokit/rest', () => ({
  Octokit: jest.fn().mockImplementation(() => ({})),
}));

import { detectAiCoAuthor } from '@/lib/github';

describe('detectAiCoAuthor', () => {
  it('returns not detected for no co-author trailer', () => {
    expect(detectAiCoAuthor('feat: add login page')).toEqual({ detected: false, tool: null });
  });

  it('returns not detected for a human co-author', () => {
    expect(detectAiCoAuthor('fix: typo\n\nCo-Authored-By: Jane Doe <jane@example.com>')).toEqual({
      detected: false,
      tool: null,
    });
  });

  const toolCases: Array<[string, string, string]> = [
    ['Claude Code (name)', 'Co-Authored-By: Claude <noreply@anthropic.com>', 'Claude Code'],
    ['Cursor (name)', 'Co-Authored-By: Cursor <noreply@cursor.sh>', 'Cursor'],
    ['GitHub Copilot (full)', 'Co-Authored-By: GitHub Copilot <copilot@github.com>', 'GitHub Copilot'],
    ['Copilot (short)', 'Co-Authored-By: Copilot <copilot@github.com>', 'GitHub Copilot'],
    ['Windsurf', 'Co-Authored-By: Windsurf <noreply@windsurf.ai>', 'Windsurf'],
    ['Aider', 'Co-Authored-By: Aider <noreply@aider.dev>', 'Aider'],
    ['Codeium', 'Co-Authored-By: Codeium <noreply@codeium.com>', 'Codeium'],
    ['Tabnine', 'Co-Authored-By: Tabnine <noreply@tabnine.com>', 'Tabnine'],
    ['Amazon Q', 'Co-Authored-By: Amazon Q <noreply@amazon.com>', 'Amazon Q'],
  ];

  it.each(toolCases)('detects %s', (_label, message, expectedTool) => {
    const result = detectAiCoAuthor(`feat: stuff\n\n${message}`);
    expect(result).toEqual({ detected: true, tool: expectedTool });
  });

  it('detects noreply@anthropic email pattern', () => {
    const result = detectAiCoAuthor('fix\n\nCo-Authored-By: Bot <noreply@anthropic.com>');
    expect(result).toEqual({ detected: true, tool: 'Claude Code' });
  });

  it('detects noreply@cursor email pattern', () => {
    const result = detectAiCoAuthor('fix\n\nCo-Authored-By: Bot <noreply@cursor.sh>');
    expect(result).toEqual({ detected: true, tool: 'Cursor' });
  });

  it('detects "Generated with Claude Code" body pattern', () => {
    const result = detectAiCoAuthor('feat: add auth\n\nGenerated with Claude Code');
    expect(result).toEqual({ detected: true, tool: 'Claude Code' });
  });

  it('detects "Generated with [Claude Code]" markdown link pattern', () => {
    const result = detectAiCoAuthor('feat: add auth\n\nGenerated with [Claude Code](https://claude.com)');
    expect(result).toEqual({ detected: true, tool: 'Claude Code' });
  });

  it('detects "Generated by Copilot" body pattern', () => {
    const result = detectAiCoAuthor('fix: stuff\n\nGenerated by Copilot');
    expect(result).toEqual({ detected: true, tool: 'GitHub Copilot' });
  });

  it('is case insensitive', () => {
    const result = detectAiCoAuthor('fix\n\nco-authored-by: claude <noreply@anthropic.com>');
    expect(result).toEqual({ detected: true, tool: 'Claude Code' });
  });

  // PR body detection — same function is used on PR bodies for merge commits
  describe('PR body patterns (used for merge commit AI detection)', () => {
    it('detects "Generated with [Claude Code]" in PR body', () => {
      const prBody = '## Summary\n- Added new feature\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)';
      expect(detectAiCoAuthor(prBody)).toEqual({ detected: true, tool: 'Claude Code' });
    });

    it('detects "Generated by Copilot" in PR body', () => {
      const prBody = '## Changes\nFixed a bug\n\nGenerated by Copilot';
      expect(detectAiCoAuthor(prBody)).toEqual({ detected: true, tool: 'GitHub Copilot' });
    });

    it('returns not detected for PR body without AI markers', () => {
      const prBody = '## Summary\n- Refactored auth module\n\n## Test plan\n- Unit tests pass';
      expect(detectAiCoAuthor(prBody)).toEqual({ detected: false, tool: null });
    });

    it('detects Co-Authored-By in PR body text', () => {
      const prBody = 'Some description\n\nCo-Authored-By: Claude <noreply@anthropic.com>';
      expect(detectAiCoAuthor(prBody)).toEqual({ detected: true, tool: 'Claude Code' });
    });
  });
});
