import { Octokit } from '@octokit/rest';

export interface CommitData {
  sha:           string;
  repo:          string;
  author:        string;
  authorName:    string;
  avatarUrl:     string;
  message:       string;      // first line
  fullMessage:   string;      // full commit message (for trailer parsing)
  diff:          string;
  additions:     number;
  deletions:     number;
  prNumber:      number | null;  // null = direct push
  prTitle:       string | null;
  committedAt:   string;
  aiCoAuthored:  boolean;     // detected AI co-author trailer
  aiToolName:    string | null; // e.g. "Claude Code", "Cursor", "GitHub Copilot"
}

export interface PRInfo {
  number:   number;
  title:    string;
  repo:     string;
  mergedAt: string;
}

export interface OrgMember {
  login:     string;
  avatarUrl: string;
}

export interface UserActivity {
  commits: CommitData[];
  prs:     PRInfo[];
}

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

// ---------- Rate limit helpers ----------

async function withRetry<T>(
  fn: () => Promise<T>,
  log?: (msg: string) => void,
  maxRetries = 5,
): Promise<T> {
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      return await fn();
    } catch (err: any) {
      const status = err?.status || err?.response?.status;
      const isRateLimit = status === 403 || status === 429;
      if (!isRateLimit || attempt === maxRetries) throw err;

      const retryAfter = err?.response?.headers?.['retry-after'];
      const resetEpoch = err?.response?.headers?.['x-ratelimit-reset'];
      let waitSec: number;
      if (retryAfter) {
        waitSec = Number(retryAfter) || 60;
      } else if (resetEpoch) {
        waitSec = Math.max(Number(resetEpoch) - Math.floor(Date.now() / 1000), 10);
      } else {
        waitSec = 30 * Math.pow(2, attempt);
      }
      log?.(`Rate limited (attempt ${attempt + 1}/${maxRetries}). Waiting ${waitSec}s…`);
      await sleep(waitSec * 1000);
    }
  }
  throw new Error('withRetry: unreachable');
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

// ---------- AI co-author detection ----------

const AI_PATTERNS: Array<{ pattern: RegExp; tool: string }> = [
  { pattern: /Co-Authored-By:.*\bClaude\b/i,            tool: 'Claude Code' },
  { pattern: /Co-Authored-By:.*\bCursor\b/i,            tool: 'Cursor' },
  { pattern: /Co-Authored-By:.*\bGitHub Copilot\b/i,    tool: 'GitHub Copilot' },
  { pattern: /Co-Authored-By:.*\bCopilot\b/i,           tool: 'GitHub Copilot' },
  { pattern: /Co-Authored-By:.*\bWindsurf\b/i,          tool: 'Windsurf' },
  { pattern: /Co-Authored-By:.*\bAider\b/i,             tool: 'Aider' },
  { pattern: /Co-Authored-By:.*\bCodeium\b/i,           tool: 'Codeium' },
  { pattern: /Co-Authored-By:.*\bTabnine\b/i,           tool: 'Tabnine' },
  { pattern: /Co-Authored-By:.*\bAmazon Q\b/i,          tool: 'Amazon Q' },
  { pattern: /Co-Authored-By:.*noreply@anthropic/i,      tool: 'Claude Code' },
  { pattern: /Co-Authored-By:.*noreply@cursor/i,         tool: 'Cursor' },
  { pattern: /Generated with \[?Claude Code\]?/i,        tool: 'Claude Code' },
  { pattern: /Generated by Copilot/i,                    tool: 'GitHub Copilot' },
];

export function detectAiCoAuthor(fullMessage: string): { detected: boolean; tool: string | null } {
  for (const { pattern, tool } of AI_PATTERNS) {
    if (pattern.test(fullMessage)) {
      return { detected: true, tool };
    }
  }
  return { detected: false, tool: null };
}

// ---------- Org members ----------

export async function listOrgMembers(
  org: string,
  log?: (msg: string) => void,
): Promise<OrgMember[]> {
  const members: OrgMember[] = [];
  for await (const res of octokit.paginate.iterator(octokit.orgs.listMembers, {
    org, per_page: 100,
  })) {
    members.push(...res.data.map((m) => ({
      login:     m.login,
      avatarUrl: m.avatar_url || '',
    })));
  }
  log?.(`Found ${members.length} org members`);
  return members;
}

// ---------- Per-user commit search ----------

interface RawCommitHit {
  sha:         string;
  repo:        string;
  message:     string;   // first line
  fullMessage: string;   // complete message
  authorLogin: string;
  authorName:  string;
  avatarUrl:   string;
  date:        string;
}

/**
 * Search all commits by a user in an org within a date range.
 * Uses the commit search API — gives the complete picture including
 * direct pushes that never went through a PR.
 */
async function searchUserCommits(
  org:   string,
  user:  string,
  since: Date,
  log?:  (msg: string) => void,
): Promise<RawCommitHit[]> {
  const sinceStr = since.toISOString().split('T')[0];
  const query    = `org:${org} author:${user} committer-date:>=${sinceStr}`;
  const hits: RawCommitHit[] = [];

  let page = 1;
  while (true) {
    await sleep(2500);
    const res = await withRetry(
      () => octokit.search.commits({
        q: query, sort: 'committer-date', order: 'desc', per_page: 100, page,
      }),
      log,
    );

    for (const item of res.data.items) {
      hits.push({
        sha:         item.sha,
        repo:        item.repository.name,
        message:     item.commit.message.split('\n')[0],
        fullMessage: item.commit.message,
        authorLogin: item.author?.login       || user,
        authorName:  item.commit.author?.name  || user,
        avatarUrl:   item.author?.avatar_url   || '',
        date:        item.commit.committer?.date || '',
      });
    }

    if (hits.length >= res.data.total_count || res.data.items.length < 100) break;
    page++;
  }
  return hits;
}

// ---------- Per-user PR search ----------

async function searchUserMergedPRs(
  org:   string,
  user:  string,
  since: Date,
  log?:  (msg: string) => void,
): Promise<PRInfo[]> {
  const sinceStr = since.toISOString().split('T')[0];
  const query    = `org:${org} type:pr is:merged author:${user} merged:>=${sinceStr}`;
  const prs: PRInfo[] = [];

  let page = 1;
  while (true) {
    await sleep(2500);
    const res = await withRetry(
      () => octokit.search.issuesAndPullRequests({
        q: query, sort: 'updated', order: 'desc', per_page: 100, page,
      }),
      log,
    );
    if (page === 1 && res.data.total_count === 0) return [];

    for (const item of res.data.items) {
      const repoFullName = item.repository_url.split('/repos/')[1] || '';
      const repo = repoFullName.split('/')[1] || '';
      prs.push({
        number:   item.number,
        title:    item.title,
        repo,
        mergedAt: item.pull_request?.merged_at || '',
      });
    }
    if (prs.length >= res.data.total_count || res.data.items.length < 100) break;
    page++;
  }
  return prs;
}

// ---------- Commit detail (diff) ----------

async function getCommitDetail(
  org:  string,
  repo: string,
  sha:  string,
  log?: (msg: string) => void,
): Promise<{ additions: number; deletions: number; diff: string }> {
  const { data } = await withRetry(
    () => octokit.repos.getCommit({ owner: org, repo, ref: sha }),
    log,
  );
  const additions = data.stats?.additions || 0;
  const deletions = data.stats?.deletions || 0;
  const patches = (data.files || [])
    .map((f) => `--- ${f.filename}\n${f.patch || ''}`)
    .join('\n');
  return { additions, deletions, diff: patches.slice(0, 4000) };
}

// ---------- Main: fetch full user activity ----------

/**
 * Fetches complete activity for a user: all commits + merged PRs.
 * Commits are enriched with diffs and matched to PRs where possible.
 */
export async function fetchUserActivity(
  org:   string,
  user:  string,
  since: Date,
  log?:  (msg: string) => void,
): Promise<UserActivity> {
  // 1. Get all commits and merged PRs in parallel-ish (with rate limit gaps)
  const rawCommits = await searchUserCommits(org, user, since, log);
  const prs        = await searchUserMergedPRs(org, user, since, log);

  // 2. Build PR lookup: repo#number → PRInfo
  //    Also parse PR refs from commit messages: "(#123)"
  const prByKey = new Map<string, PRInfo>();
  for (const pr of prs) {
    prByKey.set(`${pr.repo}#${pr.number}`, pr);
  }

  // 3. Enrich each commit with diff and PR association
  const commits: CommitData[] = [];

  // Cache PR bodies fetched for AI detection on merge commits
  const prBodyCache = new Map<string, string>();

  for (const raw of rawCommits) {
    // Try to match commit to a PR via message pattern "(#NNN)" or "Merge pull request #NNN"
    const prMatch = raw.message.match(/\(#(\d+)\)/) || raw.message.match(/^Merge pull request #(\d+)/);
    let prNumber: number | null = null;
    let prTitle:  string | null = null;

    if (prMatch) {
      const key = `${raw.repo}#${prMatch[1]}`;
      const pr  = prByKey.get(key);
      if (pr) {
        prNumber = pr.number;
        prTitle  = pr.title;
      } else {
        // PR ref in message but not in our PR search — still mark it
        prNumber = Number(prMatch[1]);
      }
    }

    // Detect AI co-author from full commit message
    let ai = detectAiCoAuthor(raw.fullMessage);

    // For merge commits with a PR: also check PR body and branch commit trailers
    if (!ai.detected && prNumber && raw.message.startsWith('Merge pull request #')) {
      const cacheKey = `${raw.repo}#${prNumber}`;
      let prBody = prBodyCache.get(cacheKey);
      if (prBody === undefined) {
        try {
          const { data: prData } = await withRetry(
            () => octokit.pulls.get({ owner: org, repo: raw.repo, pull_number: prNumber! }),
            log,
          );
          prBody = prData.body || '';
          prBodyCache.set(cacheKey, prBody);
        } catch {
          prBody = '';
          prBodyCache.set(cacheKey, prBody);
        }
      }
      if (prBody) {
        ai = detectAiCoAuthor(prBody);
      }

      // If still not detected, check the branch commits' trailers
      if (!ai.detected) {
        try {
          const { data: prCommits } = await withRetry(
            () => octokit.pulls.listCommits({ owner: org, repo: raw.repo, pull_number: prNumber!, per_page: 50 }),
            log,
          );
          for (const pc of prCommits) {
            const branchAi = detectAiCoAuthor(pc.commit.message);
            if (branchAi.detected) {
              ai = branchAi;
              break;
            }
          }
        } catch {
          // proceed without branch commit check
        }
      }
    }

    // Fetch diff
    let diff = '', additions = 0, deletions = 0;
    try {
      const detail = await getCommitDetail(org, raw.repo, raw.sha, log);
      diff      = detail.diff;
      additions = detail.additions;
      deletions = detail.deletions;
    } catch {
      // proceed without diff
    }

    commits.push({
      sha:          raw.sha,
      repo:         raw.repo,
      author:       raw.authorLogin,
      authorName:   raw.authorName,
      avatarUrl:    raw.avatarUrl,
      message:      raw.message,
      fullMessage:  raw.fullMessage,
      diff,
      additions,
      deletions,
      prNumber,
      prTitle,
      committedAt:  raw.date,
      aiCoAuthored: ai.detected,
      aiToolName:   ai.tool,
    });
  }

  return { commits, prs };
}
