export const TIPS: string[] = [
  // Code quality & complexity (1-26)
  "High complexity scores often indicate meaningful engineering work — don't penalize developers for tackling hard problems.",
  "Lines of code deleted can be more valuable than lines added. Celebrate thoughtful removal.",
  "A spike in code churn usually signals unclear requirements, not poor developers.",
  "Track cyclomatic complexity trends per repo, not absolute values. Context matters.",
  "Reward teams that reduce complexity without changing behavior. That's pure engineering skill.",
  "If your hottest files are also your most complex, you have a ticking time bomb.",
  "Code quality isn't binary. Use a spectrum: fragile, adequate, robust, resilient.",
  "Large functions aren't always bad — but large functions that change frequently are.",
  "Don't confuse verbosity with clarity. The best code communicates intent in minimal lines.",
  "A repo with zero lint warnings and terrible architecture is still a liability.",
  "Track the ratio of test code to production code. Below 0.3 is a red flag.",
  "High-quality code is code your team can modify confidently six months from now.",
  "If every PR touches the same five files, your architecture has a coupling problem.",
  "Measure code duplication trends, not snapshots. A rising trend matters more than the current number.",
  "The most dangerous code is code nobody wants to touch. Track file ownership gaps.",
  "A clean git blame tells a story. Messy blame histories suggest unclear ownership.",
  "Complexity per commit is more revealing than complexity per file.",
  "Static analysis tools catch syntax issues. Only humans catch design flaws. Invest in both.",
  "When a single file exceeds 500 lines, it's usually doing too much. Track file size distributions.",
  "Dead code is technical debt with zero upside. Automate its detection.",
  "If your test suite takes over 20 minutes, developers will stop running it locally.",
  "Code coverage above 90% often means you're testing implementation details, not behavior.",
  "Track how often builds break after merges. Frequent breaks signal integration testing gaps.",
  "The best indicator of code quality is how fast a new team member can ship their first PR.",
  "Functions with more than four parameters are begging for a refactor.",
  "Watch for \"shotgun surgery\" patterns — when one change requires edits across many files.",

  // PR discipline (27-52)
  "Direct pushes to main should trigger an alert, not just a log entry.",
  "Track your team's PR merge-without-approval rate. Anything above 5% needs attention.",
  "PRs open longer than 5 days are 3x more likely to cause merge conflicts.",
  "The ideal PR size is 200-400 lines. Beyond that, review quality drops sharply.",
  "A PR with zero comments isn't a sign of quality — it's a sign nobody read it.",
  "Track time-to-first-review. If it exceeds 24 hours, your review culture has a bottleneck.",
  "Self-merges should be the exception, not the rule. Set a team threshold and enforce it.",
  "The number of review cycles per PR reveals how well specs are communicated upfront.",
  "If one person approves 80% of PRs, you have a bus factor of one on code review.",
  "Require at least two reviewers on PRs touching auth, payments, or data pipelines.",
  "Track PR rejection rates. Too low means rubber-stamping; too high means poor planning.",
  "Draft PRs are underused. Encourage early feedback before code is \"done.\"",
  "Review turnaround time is a team health metric, not just a productivity metric.",
  "PRs that skip CI checks are the ones most likely to cause incidents.",
  "A healthy team has a PR approval distribution across at least 3-4 reviewers.",
  "Track how many PRs get approved on the first review cycle. That's a quality signal.",
  "Stacked PRs reduce review burden and ship faster. Coach your team to use them.",
  "If your average PR description is under two sentences, your review culture needs work.",
  "Monitor weekend and late-night PR merges. They correlate with incident rates.",
  "The best code reviewers aren't the fastest — they're the ones who catch design issues.",
  "Track the ratio of review comments that lead to code changes vs. those dismissed.",
  "Force-pushes to shared branches destroy context. Ban them in team agreements.",
  "A healthy PR pipeline has a consistent flow, not boom-bust cycles before deadlines.",
  "Pair programming can replace some code reviews — but track that it actually happens.",
  "If PRs routinely need 3+ review cycles, invest in better design docs upfront.",
  "Auto-assign reviewers based on file ownership to reduce review bottlenecks.",

  // AI-assisted coding (53-78)
  "Track what percentage of your team's code is AI-assisted. The trend matters more than the number.",
  "AI-generated code that skips review is the fastest path to production incidents.",
  "Developers using AI tools ship more PRs — but check if those PRs are also larger and less tested.",
  "AI adoption isn't uniform. Identify your early adopters and pair them with skeptics.",
  "The best AI-assisted workflows still have a human reviewing every generated test.",
  "If AI-generated code has a higher revert rate, your team needs better prompting practices.",
  "Track AI tool usage per repo. Some codebases benefit more from AI than others.",
  "AI excels at boilerplate. If your team uses AI mostly for core logic, watch quality closely.",
  "Developers who over-rely on AI suggestions often produce code they can't debug.",
  "Measure time-to-merge for AI-assisted PRs vs. manual ones. Faster isn't always better.",
  "AI code completion tools increase velocity but can mask skill gaps in junior developers.",
  "Create a team policy on when AI-generated code requires additional review scrutiny.",
  "The real AI productivity gain is in test generation and documentation, not feature code.",
  "Track which AI suggestions get accepted vs. rejected. Low acceptance rates waste time.",
  "AI-assisted refactoring is powerful — but validate that behavior is preserved with tests.",
  "If your AI tool suggests code that violates your style guide, fix your AI configuration first.",
  "AI-generated commit messages are usually too generic. Coach your team to edit them.",
  "Monitor the complexity of AI-generated code. It tends toward verbose, obvious solutions.",
  "Teams that pair AI tools with strong linting catch more issues than either alone.",
  "AI can write the code, but only humans can judge whether it should exist at all.",
  "Track how much time developers spend reviewing AI suggestions vs. writing from scratch.",
  "AI-generated tests often test the implementation, not the contract. Review them carefully.",
  "The fastest-adopting AI teams also have the strongest code review cultures. That's not a coincidence.",
  "Use AI to generate PR descriptions from diffs — but always have the author verify.",
  "AI tools are most valuable in mature codebases with clear patterns to learn from.",
  "Don't measure AI adoption by tool installs. Measure it by accepted suggestions per day.",

  // Team dynamics (79-105)
  "Comparing teams by raw output is misleading. Normalize by project complexity and team size.",
  "Your top performer's habits should be documented and shared, not just celebrated.",
  "A team where one person does 60% of reviews has a knowledge-sharing problem.",
  "The gap between your fastest and slowest PR reviewers reveals mentoring opportunities.",
  "Consistently low performers often lack context, not ability. Check their onboarding experience.",
  "Track contribution distribution. Healthy teams have a Gini coefficient below 0.4.",
  "Cross-team PR reviews build shared context and prevent knowledge silos.",
  "If a team's velocity drops after someone leaves, they had undocumented tribal knowledge.",
  "New hires who ship their first PR in week one stay longer than those who wait a month.",
  "Pair your strongest reviewers with your newest team members for maximum growth.",
  "Teams that do weekly code walkthroughs have 30% fewer recurring bugs.",
  "If two teams own overlapping code, one of them will eventually stop maintaining it.",
  "Track how evenly on-call burden is distributed. Uneven distribution causes attrition.",
  "The best teams have overlapping knowledge, not siloed expertise.",
  "A senior engineer who only writes code and never reviews is underperforming their role.",
  "High-performing teams have shorter feedback loops, not longer work hours.",
  "Watch for \"hero culture\" — when one person always saves the sprint. That's a systemic failure.",
  "Compare teams by outcomes delivered per quarter, not story points completed.",
  "If your team's bus factor is below 2 for any critical system, that's your top priority.",
  "Teams with rotating tech leads develop more well-rounded engineers.",
  "Track the ratio of collaborative PRs (co-authored) to solo PRs. More collaboration usually means better code.",
  "A team that never disagrees in code review isn't being honest.",
  "Meeting load inversely correlates with commit frequency. Protect maker time.",
  "The quietest person on your team might be your most careful code reviewer.",
  "Celebrate the developer who finds the bug before production, not just the one who fixes it.",
  "Track mentoring hours the same way you track coding hours. Both drive team output.",
  "When a strong performer's review quality drops, check their workload before their motivation.",

  // Developer productivity (106-131)
  "Commit frequency is a health signal, not a productivity metric. Erratic patterns suggest blockers.",
  "Developers who commit daily ship more reliably than those who batch weekly.",
  "A sudden drop in commit frequency often precedes burnout by 2-3 weeks.",
  "Track first-commit-of-the-day time. Consistent late starts can signal disengagement.",
  "Context switching costs 20-30 minutes per switch. Track how many repos a dev touches daily.",
  "Long-lived feature branches are productivity killers. Encourage trunk-based development.",
  "If a developer's PR size doubles overnight, they're probably batching due to process friction.",
  "Focus time blocks correlate with higher code quality. Measure meeting-free hours per developer.",
  "Track the gap between PR submission and first review. That's idle time for the author.",
  "Developers who write tests first have fewer reverts. Track test-before-code patterns.",
  "Weekend commits are a burnout signal, not a dedication signal. Address the root cause.",
  "Velocity spikes before deadlines followed by crashes after are a sign of unsustainable pace.",
  "Track cycle time from first commit to production deploy. That's your true throughput metric.",
  "A developer with high commit frequency but low merge rate is stuck in review limbo.",
  "Measure wait time in your pipeline: review waits, CI waits, deploy waits. Eliminate the longest.",
  "If your fastest developer is 10x more productive, ask what's slowing everyone else down.",
  "Consistency beats intensity. The developer who ships every day outperforms the one who sprints and crashes.",
  "Track how long it takes to go from idea to first commit. Long gaps indicate planning overhead.",
  "A developer touching too many repos at once is spread too thin. Consolidate their focus.",
  "Late-night commits correlate with higher bug rates. Track after-hours coding patterns.",
  "The best productivity intervention is often removing one meeting per day.",
  "If your team's deployment frequency is below once a week, find the bottleneck.",
  "Track time spent on code review vs. writing code. Top teams spend 20-30% on reviews.",
  "Auto-merge for trivial changes (typos, config bumps) frees review bandwidth for what matters.",
  "Monitor IDE time vs. meeting time ratios. Below 50% coding time signals process bloat.",
  "The developer who refactors before adding features is saving your team future hours.",

  // Engineering metrics (132-157)
  "Commit count is a vanity metric. Impact per commit tells you what actually matters.",
  "DORA metrics are a starting point, not the destination. Customize for your team's context.",
  "Track deployment frequency, lead time, change failure rate, and recovery time together — not in isolation.",
  "A dashboard nobody checks is worse than no dashboard. Measure engagement with your own tools.",
  "Velocity metrics without quality metrics incentivize the wrong behavior.",
  "The most dangerous metric is the one your team optimizes for at the expense of everything else.",
  "Track the ratio of feature work to maintenance work. Below 60% features signals tech debt crisis.",
  "Story points measure effort, not value. Track business outcomes alongside engineering metrics.",
  "If your metrics don't change anyone's behavior, they're decorative, not actionable.",
  "Mean time to recovery matters more than mean time between failures for mature teams.",
  "Track the percentage of time spent on unplanned work. Above 30% means your planning is off.",
  "Measure rework rate: the percentage of code changed within two weeks of being written.",
  "The best engineering metrics are ones your team agrees are fair and useful.",
  "High deployment frequency with high change failure rate is just shipping bugs faster.",
  "Track PR throughput per week as a team, not per individual. Teams ship, not people.",
  "An impact score should weigh complexity, risk, and business value — not just lines changed.",
  "If you can't explain why a metric matters in one sentence, drop it from your dashboard.",
  "Leading indicators (PR size trends, test coverage changes) beat lagging indicators (incident count).",
  "Benchmark against your own past performance, not other companies. Context is everything.",
  "Track the percentage of work that's developer-initiated vs. externally-requested. Both matter.",
  "Measure how long it takes a new feature to reach 90% of users after merge.",
  "If your dashboard has more than 7 metrics, nobody is reading all of them.",
  "Track the age of your oldest open PR. It reveals process bottlenecks.",
  "Metric targets should be ranges, not exact numbers. Precision creates gaming.",
  "The best metric for team health is whether developers would recommend the team to a friend.",
  "Track escaped defects: bugs found in production that should have been caught in review or testing.",

  // LLM/AI governance (158-183)
  "Every AI-generated PR should be tagged so you can measure its lifecycle differently.",
  "Set a governance policy before AI adoption scales, not after the first incident.",
  "Track what percentage of AI-generated code passes review on the first try.",
  "AI-generated code in security-sensitive areas should require an additional human reviewer.",
  "Velocity gains from AI mean nothing if your change failure rate rises alongside them.",
  "Create an AI usage policy that specifies which repos and file types allow AI-generated code.",
  "Review burden increases with AI adoption. Staff accordingly or automate triage.",
  "Track revert rates for AI-assisted commits separately. The data will guide your policy.",
  "AI governance isn't about restricting use — it's about ensuring quality at higher velocity.",
  "If AI-generated code bypasses your test requirements, your CI pipeline has a gap.",
  "The governance-velocity balance is your most important calibration as AI adoption grows.",
  "Require AI-generated code to meet the same review standards as human-written code. No exceptions.",
  "Track AI tool versions across your team. Inconsistent tooling creates inconsistent output.",
  "Audit AI-generated code for license compliance. Copilot suggestions can include licensed snippets.",
  "Monitor which developers override AI suggestions most. They may have insights worth sharing.",
  "AI-generated documentation should be verified by the feature owner, not just merged.",
  "Track the mean time to detect issues in AI-generated vs. human-written code.",
  "Your AI governance policy should evolve quarterly as tools and team maturity change.",
  "If AI-generated PRs have lower review engagement, reviewers may be trusting the tool too much.",
  "Create separate metrics dashboards for AI-assisted and manual workflows to spot divergence.",
  "AI code generation without architecture awareness creates locally correct but globally incoherent systems.",
  "Track how AI adoption affects your team's code review depth. Shorter reviews aren't always better.",
  "Ban AI-generated code in incident response. Speed under pressure needs human judgment.",
  "Measure the ratio of AI-generated code that survives six months without modification.",
  "Your AI governance framework should include rollback procedures for AI-tooling outages.",
  "If AI tools are generating your tests, who tests the tests? Define that responsibility explicitly.",

  // Technical leadership (184-210)
  "The best hiring signal for senior engineers is how they talk about past failures, not successes.",
  "Onboarding should include a curated first PR, not just documentation reading.",
  "A new hire's first week should end with a shipped change, however small.",
  "Knowledge sharing isn't optional for senior engineers. Make it a performance criterion.",
  "Track how long it takes new hires to make their first unassisted production deploy.",
  "The best tech leads write less code and enable more people to write better code.",
  "If your architecture decisions aren't documented, they'll be reversed within two years.",
  "Run blameless postmortems within 48 hours of an incident, not after the next sprint.",
  "Invest in internal developer tools proportional to team size. Above 20 engineers, it's non-negotiable.",
  "Technical debt should have a dedicated budget, not compete with feature work.",
  "The most valuable tech lead skill is saying no to the right things at the right time.",
  "Track onboarding time-to-productivity. If it's over 90 days, simplify your codebase or your process.",
  "Engineering managers who stop reading code lose the ability to evaluate technical decisions.",
  "Create a decision log for architectural choices. Future you will be grateful.",
  "The best teams have explicit coding standards documented, not just implied.",
  "Succession planning means no single person's departure should delay a project by more than a sprint.",
  "If your team leads spend more than 30% of time in meetings, they can't lead technically.",
  "Hire for the team's gaps, not the candidate's strengths. Balance matters more than stars.",
  "A good engineering manager knows the difference between a slow week and a systemic problem.",
  "Invest in writing culture. Teams that write well ship more predictable software.",
  "Track how many internal tech talks your team gives per quarter. Knowledge sharing compounds.",
  "Your architecture should make the right thing easy and the wrong thing hard.",
  "Engineering leaders who never pair-program with their team miss critical context.",
  "Make on-call rotations a learning experience, not a punishment.",
  "The cost of a bad hire is 6-12 months of team disruption. Invest in your interview process.",
  "If your team can't explain the system architecture in 5 minutes, it's too complex.",
  "Promote engineers who elevate others, not just those who ship the most code.",

  // Code review best practices (211-236)
  "Review the design before the code. A well-implemented bad idea is still a bad idea.",
  "Limit code reviews to 60 minutes at a time. Quality drops sharply after that.",
  "Use a review checklist for critical paths: security, performance, error handling, observability.",
  "Nitpicks should be labeled as such. Don't block a PR for style preferences.",
  "Ask \"what happens if this fails?\" on every error path. Most bugs live there.",
  "Review tests first. If the tests make sense, the implementation usually does too.",
  "Approve with comments when changes are minor. Don't force another review cycle for typos.",
  "Track how many review comments are questions vs. suggestions vs. requirements.",
  "The reviewer's job is to understand the code, not to rewrite it in their style.",
  "If you can't review a PR in under 30 minutes, it's probably too large.",
  "Automate style enforcement. Humans should review logic, not formatting.",
  "Leave at least one positive comment per review. It costs nothing and builds trust.",
  "Review PRs in the order they were submitted, not by author or priority.",
  "If a PR description says 'minor changes' but the diff is 500 lines, push back.",
  "Require reviewers to pull and run code locally for changes above 200 lines.",
  "Don't approve code you don't understand. Ask questions — that's the point of review.",
  "Track how often reviewed code causes incidents vs. unreviewed code. The data speaks.",
  "Use PR templates to ensure context, testing notes, and rollback plans are always included.",
  "The best review comment teaches something. The worst one just says 'change this.'",
  "Review for missing code as much as for existing code. What's not there matters.",
  "Encourage authors to self-review before requesting others. It catches 30% of issues.",
  "Set expectations on review SLAs: 4 hours for small PRs, 24 hours for large ones.",
  "Rotating review assignments prevents knowledge silos and distributes learning.",
  "If a reviewer always approves without comments, they're not reviewing — they're rubber-stamping.",
  "Code review is a conversation, not a gatekeeping exercise.",
  "Track the average number of review iterations per PR. More than 3 suggests misalignment.",

  // Incident prevention & risk management (237-262)
  "Track which repos have the highest incident rate. Invest in hardening those first.",
  "Every incident should produce at least one automated check that prevents recurrence.",
  "Monitor deploy frequency vs. incident frequency. If they correlate, your testing is insufficient.",
  "The riskiest deploys happen on Fridays. Track day-of-week incident distribution.",
  "If your rollback takes longer than 5 minutes, it's not a real rollback.",
  "Track the number of hotfixes per sprint. More than two signals a quality problem.",
  "Feature flags reduce deploy risk. Track what percentage of new features use them.",
  "The most dangerous change is the one everyone assumes is safe. Review 'trivial' changes too.",
  "Track mean time to detect, not just mean time to resolve. Fast detection saves everything.",
  "Canary deployments catch issues before they become incidents. Measure canary coverage.",
  "If your on-call engineer can't diagnose issues without the original author, documentation is lacking.",
  "Track which types of changes cause the most incidents: schema migrations, config changes, dependency updates.",
  "A rising escaped-defect rate means your pre-production safety nets have holes.",
  "Run chaos engineering exercises quarterly. The bugs you find in practice are cheaper than production incidents.",
  "Track how many incidents are caused by direct pushes vs. reviewed PRs.",
  "If your team's change failure rate exceeds 15%, slow down and invest in quality.",
  "Monitor dependency vulnerability counts weekly. Unpatched dependencies are incidents waiting to happen.",
  "Track the age of your oldest unresolved security finding. Time is the attacker's advantage.",
  "Require a rollback plan for every deploy. If you can't write one, the change is too risky.",
  "Post-incident reviews that don't produce action items are just storytelling sessions.",
  "Track how many incidents were predictable from existing monitoring data. That gap is your opportunity.",
  "Load test before major launches, not after the first outage.",
  "If your alerting generates more than 5 false positives per week, on-call fatigue will cause missed real alerts.",
  "Track the ratio of proactive fixes (found internally) to reactive fixes (found by users).",
  "Every critical path should have at least two engineers who can debug it at 3 AM.",
  "The best incident prevention is reducing the blast radius of every change.",

  // Documentation & knowledge management (263-288)
  "If it's not documented, it doesn't exist. Track documentation coverage per service.",
  "Outdated documentation is worse than no documentation. Track doc freshness alongside code changes.",
  "Every API endpoint should have documentation that a new hire can understand.",
  "README files should answer: what does this do, how do I run it, and who owns it.",
  "Track how often documentation is updated alongside the code it describes.",
  "Architecture Decision Records cost 30 minutes to write and save weeks of future debate.",
  "If onboarding requires a walkthrough from a specific person, that knowledge isn't documented.",
  "Runbooks should be tested quarterly. An untested runbook is a false sense of security.",
  "Track which docs get the most views. That tells you what people actually need.",
  "Inline code comments should explain why, not what. The code already says what.",
  "Auto-generate API docs from code annotations. Manual API docs drift within weeks.",
  "Every incident postmortem should update the relevant runbook or create a new one.",
  "Track the time between a code change and its documentation update. Same-day is the goal.",
  "Documentation PRs should be reviewed with the same rigor as code PRs.",
  "If a developer searches your docs and finds nothing, that's a documentation bug.",
  "Create a glossary of team-specific terms. Jargon is the enemy of onboarding.",
  "Track knowledge bus factor per service. If only one person can explain a system, document it now.",
  "Video walkthroughs of complex systems are 10x more effective than written docs for onboarding.",
  "Treat internal docs like a product: track usage, gather feedback, iterate.",
  "Decision logs prevent the same debates from recurring every six months.",
  "Every service should have a one-page architecture overview updated quarterly.",
  "If your team spends more than 10% of time answering the same questions, write a FAQ.",
  "Link code comments to design docs. Future readers need context, not just code.",
  "Track how many Slack questions could have been answered by existing documentation.",
  "Deprecation notices should include migration guides, not just sunset dates.",
  "The best documentation is written by someone who just learned the system, not the person who built it.",

  // CI/CD & developer experience (289-314)
  "If your CI pipeline takes more than 15 minutes, developers will context-switch during builds.",
  "Track flaky test rates weekly. Above 2% flakiness erodes trust in the entire suite.",
  "Every failed build should produce an actionable error message, not a stack trace.",
  "Measure the time from merge to production deploy. That's your delivery bottleneck metric.",
  "If developers need more than 3 commands to set up a local environment, simplify it.",
  "Track how often developers re-run CI due to flaky failures. That's wasted time and compute.",
  "Cache aggressively in CI. Build minutes are developer patience minutes.",
  "A CI pipeline that only runs on merge is too late. Run checks on every push.",
  "Track the percentage of deployments that are fully automated vs. require manual steps.",
  "Monitor build queue wait times. Long queues mean your team is bigger than your CI capacity.",
  "Parallelize test suites. A 30-minute serial suite often runs in 8 minutes parallelized.",
  "Track which CI steps fail most often. Optimize or fix the top three.",
  "Preview environments for every PR accelerate review quality and reduce staging bottlenecks.",
  "If your deploy requires a specific person's credentials, you have a single point of failure.",
  "Measure developer satisfaction with your CI/CD pipeline quarterly. Tools should serve the team.",
  "Track how many deploys are rolled back within an hour. That's your change failure rate in real-time.",
  "Developers who can deploy confidently deploy more often. Invest in deployment safety nets.",
  "Auto-format on commit so CI never fails for style. Save human review for substance.",
  "If your staging environment doesn't match production, it's giving you false confidence.",
  "Track the gap between \"works on my machine\" and \"works in CI.\" That gap is lost productivity.",
  "Every team should own their own deployment pipeline. Shared pipelines create shared bottlenecks.",
  "Measure the ratio of build time to test time. If builds dominate, optimize your build toolchain.",
  "Feature flag cleanup should be part of your CI. Stale flags are dead code with runtime risk.",
  "Track how many config changes require a full redeploy. Zero should be the goal.",
  "Developer experience is a retention strategy. Track DX satisfaction scores alongside engagement surveys.",
  "If setting up a new microservice takes more than a day, invest in service templates.",

  // Refactoring & tech debt (315-340)
  "Track tech debt as a first-class backlog item with estimated interest payments.",
  "Allocate 20% of sprint capacity to tech debt reduction. Below that, debt compounds faster than you pay it down.",
  "The best time to refactor is when you're already changing the code for a feature.",
  "Track the age of your oldest TODO comment. If it's over a year, it's not a TODO — it's a lie.",
  "Refactoring without tests is just rearranging code and hoping. Write tests first.",
  "Measure the time-to-modify for your most-changed files. Rising times signal hardening debt.",
  "If a refactor doesn't improve a measurable quality (speed, readability, testability), skip it.",
  "Track how much of each sprint is spent working around existing tech debt.",
  "Large refactors should be broken into incremental PRs. Big bang rewrites usually fail.",
  "Monitor dependency age. Libraries more than two major versions behind are a security and compatibility risk.",
  "If a module has more workarounds than features, it's time to rewrite it.",
  "Track how often tech debt items are deferred. Three deferrals means it's not really prioritized.",
  "Strangler fig pattern beats big-bang rewrites. Replace incrementally and reduce risk.",
  "Code that hasn't been modified in two years either works perfectly or is completely abandoned. Find out which.",
  "Tech debt sprints sound good but don't work. Integrate debt reduction into every sprint instead.",
  "Track the ratio of new features to refactoring commits. Healthy teams maintain a 70/30 balance.",
  "Every tech debt item should have a cost estimate: how much extra time does it add to each change?",
  "If your abstractions require more code than the thing they abstract, remove them.",
  "Monitor deprecated API usage in your codebase. Every deprecated call is a future migration headache.",
  "Reward engineers who make unglamorous infrastructure improvements. They're the real MVPs.",
  "Tech debt retrospectives should happen quarterly with stakeholders who approve the time investment.",
  "Track the number of \"temporary\" solutions that have been in production for over six months.",
  "Before refactoring, define success criteria. Otherwise you'll refactor forever.",
  "The cost of tech debt is measured in developer frustration, not just engineering hours.",
  "If your test suite needs refactoring too, prioritize that — broken tests hide broken code.",
  "Track which teams consistently reduce tech debt vs. those that only add it.",

  // Open source & community (341-366)
  "Track which open-source dependencies your team relies on most. Consider sponsoring them.",
  "Contributing upstream fixes is cheaper than maintaining permanent patches internally.",
  "Monitor your team's open-source contributions. They signal engineering maturity and goodwill.",
  "If your most critical dependency has one maintainer, that's a risk worth tracking.",
  "Open-source your internal tools when possible. External contributions improve quality.",
  "Track how often your team forks vs. contributes upstream. Forks are tech debt in disguise.",
  "Inner-source practices (open PRs across teams) improve code quality and reduce silos.",
  "The best developers often contribute to open source. Encourage it with dedicated time.",
  "Track dependency license compliance automatically. A manual process will miss something.",
  "Before adopting a new dependency, check its maintenance pulse: recent commits, open issues, response time.",
  "Open-source contributions are a hiring signal. Candidates with public code give you a real portfolio.",
  "If you're wrapping an open-source tool with heavy customization, consider contributing those features upstream.",
  "Track your team's external visibility: blog posts, talks, and open-source repos. It compounds into hiring advantage.",
  "Inner-source documentation standards should match external open-source standards.",
  "An internal package registry prevents teams from reinventing the same utilities.",
  "Track how quickly your team responds to security advisories in open-source dependencies.",
  "Encourage your team to file issues on open-source projects, not just work around bugs silently.",
  "Open-source maintainer burnout is real. Rotate ownership of company-sponsored projects.",
  "Track the ratio of dependencies with active maintenance vs. those that are effectively abandoned.",
  "If a critical dependency hasn't been updated in a year, evaluate alternatives proactively.",
  "Community engagement is a leading indicator of dependency health. Monitor stars, forks, and contributor count trends.",
  "Create an internal \"approved dependencies\" list and review additions quarterly for risk.",
  "Contributing to the open-source tools you use builds expertise your team can't get any other way.",
  "Track how many internal tools could benefit other companies. Open-sourcing them is free marketing.",
  "Good documentation for internal libraries attracts internal adopters, just like open source.",
  "The healthiest engineering cultures treat their internal codebase with the same care as public open source.",
];
